version: '3,8'

services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile

  tester:
    build:
      context: ./test/
      dockerfile: Dockerfile
    depends_on:
      - builder
    command: pytest -s -v